spring.application.name=multi-db-sync-service

# Use forward slashes even on Windows for JDBC URLs

spring.datasource.driver-class-name=org.sqlite.JDBC

#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.database-platform=com.example.multidbsyncservice.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Also update the sync directory to the absolute path

spring.datasource.url=jdbc:sqlite:C:/Users/SystemiX-F-4/Desktop/node-multi-db-simulator 2/node-multi-db-simulator/databases/central-hub.db?date_string_format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
sync.db.directory=C:/Users/SystemiX-F-4/Desktop/node-multi-db-simulator 2/node-multi-db-simulator/databases
sync.db.prefix=source
sync.db.count=10

logging.config=classpath:logback-spring.xml
